### ISSUE TITLE
Impact Background Image

### ISSUE THREAD

**Issue by sydneydowd** [sydneydowd/project-athena#1]
@norr0065 @chenise-paquette @eringraham 

Having trouble getting the impact image to be responsive , when I give the image height: auto and width: 100% the navigation toggle shows in small screen. 

If anyone has time can you try troubleshooting or give suggestions ,

Thanks ladies !! 

xoxox

**Comment by chenise-paquette** [comment]
Found this on stackoverflow. Give it a try: 

background-repeat: no-repeat;  
 position: relative;  
 width: 85%;  
 height: 610px;  
 margin-left: auto;  
 margin-right: auto;

**Comment by sydneydowd** [comment]
Did seem to work , ill keep trying though

**Comment by sydneydowd** [comment]
Didnt *

**Comment by sydneydowd** [comment]
@norr0065
