### ISSUE TITLE
Link donate button to 'thankyou.html' page

### ISSUE THREAD

**Issue by chenise-paquette** [sydneydowd/project-athena#14]
Does know how to link a button to a submission button?
Here is my html for the button:

![screen shot 2016-03-02 at 5 09 03 pm](https://cloud.githubusercontent.com/assets/6371031/13477242/80d3e14a-e099-11e5-8df8-0155f5cc8a52.png)

**Comment by sydneydowd** [comment]
use href and link the thank you page to it
