### ISSUE TITLE
Button Flow

### ISSUE THREAD

**Issue by sydneydowd** [sydneydowd/project-athena#15]
Make sure that all buttons are connected to a page and it goes with the sit map

**Comment by sydneydowd** [comment]
Not sure how to link the buttons

**Comment by sydneydowd** [comment]
.get-started {
   @include button;
     &:hover, &:active &:focus {
     background-color: $white;
     color: $navy;

@eringraham

**Comment by eringraham** [comment]
<a href="{{site.baseurl}}/index.html"><button class="involvedbtn" type="button">Register Here</button></a>

**Comment by eringraham** [comment]
fix

**Comment by eringraham** [comment]
<a href="{{site.baseurl}}/index.html"><button class="involvedbtn" type="button">Register Here</button></a>

**Comment by eringraham** [comment]
<a href="{{site.baseurl}}/index.html"><button class="involvedbtn" type="button">Register Here</button></a>

**Comment by eringraham** [comment]
<a href="{{site.baseurl}}/index.html"><button class="involvedbtn" type="button">Register Here</button></a>

**Comment by eringraham** [comment]
< a href ="{{site.baseurl}}/index.html"><button class="involvedbtn" type="button"></button>< /a >
